/*
    ChibiOS - Copyright (C) 2006..2018 Giovanni Di Sirio

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/**
 * Program that prints "Hello" when a serial terminal is opened. Make sure that
 * the baudrate is 115200.
 */

#define ARM_MATH_CM4
#include "ch.h"
#include "hal.h"
#include "chprintf.h"
#include "arm_math.h"
#define MAX_BLOCKSIZE 6

// Serial driver config
static SerialConfig sd2Config = {
		115200, 					/* Baudrate */
		0,
		USART_CR2_STOP1_BITS,
		0
};

/* ----------------------------------------------------------------------
* Test input data for Floating point Dot Product example for 32-blockSize
* Generated by the MATLAB randn() function
* ------------------------------------------------------------------- */
/* ----------------------------------------------------------------------
** Test input data of srcA for blockSize 32
** ------------------------------------------------------------------- */
float32_t srcBufferA_int16t[MAX_BLOCKSIZE] =
{
		1.0, 2.0, 3.0,
		4.0, 5.0, 6.0
};

/* ----------------------------------------------------------------------
** Test input data of srcB for blockSize 32
** ------------------------------------------------------------------- */
float32_t srcBufferB_int16t[MAX_BLOCKSIZE] =
{
		1.0, 2.0, 3.0,
		4.0, 5.0, 6.0
};

/* ----------------------------------------------------------------------
* Declare Global variables
* ------------------------------------------------------------------- */
float32_t multOutput[MAX_BLOCKSIZE];  /* Intermediate output */
float32_t testOutput;  /* Final ouput */

/*
 * Application entry point.
 */
int main(void) {
  /*
   * System initialisations.
   * - HAL initialisation, this also initialises the configured device drivers
   *   and performs the board-specific initialisations.
   * - Kernel initialisation, the main() function becomes a thread and the
   *   RTOS is active.
   */
  halInit();
  chSysInit();

  // Set the GPIOA_PIN2(PA2) pin on STM32F4 board as TX.
  // The alternate function table of GPIO's can be seen at
  // https://github.com/parzival2/STM32F4-Evaluation-Board-Free-IO-Pinouts
  palSetPadMode(GPIOA, 2, PAL_MODE_ALTERNATE(7));
  // Likewise set the GPIO_PIN3(PA3) pin on STM32F4 boards as RX
  palSetPadMode(GPIOA, 3, PAL_MODE_ALTERNATE(7));
  // This is needed to start the driver. It takes the struct SerialConfig as input.
  sdStart(&SD2, &sd2Config);

  /* Multiplication of two input buffers */
  arm_mult_f32(srcBufferA_int16t, srcBufferB_int16t, multOutput, MAX_BLOCKSIZE);

/*  Accumulate the multiplication output values to
       get the dot product of the two inputs
*/
  for(uint32_t i=0; i< MAX_BLOCKSIZE; i++)
  {
     arm_add_f32(&testOutput, &multOutput[i], &testOutput, 1);
  }

  /*
   * Normal main() thread activity, it changes the GPT4 period every
   * five seconds.
   */
  while (true) {
	  chprintf((BaseSequentialStream*)&SD2, "Hello\r\n");
	  chprintf((BaseSequentialStream*)&SD2, "\n\r: %f", testOutput);
	  palTogglePad(GPIOD, GPIOD_LED4);
	  chThdSleepMilliseconds(1000);
  }
}
